package de.novatec.cg.sc.hanabi.common.enums;

public enum ResponseType {
    ERROR_RESPONSE, CONNECTION_RESPONSE, DISCARD_CARD_RESPONSE, PLAY_CARD_RESPONSE, HINT_COLOR_RESPONSE, HINT_NUMBER_RESPONSE, GAME_OVER_RESPONSE;
}
